apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "python-chart.fullname" . }}
  labels:
    {{- include "python-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
       {{- include "python-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "python-chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name:  {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: {{ .Values.containerPort}}
        envFrom:
         - configMapRef:
             name: config-map